JWT_SECRET: u-AKXHaiimSGvMraD59g9z6dVlk0DloB7SS31E5rAbxxqIMOEgqKaASJ8jeDlJNbCVWTecrzPlImOrFLwWNbCh1Uuu1ttbO1z062V4Iwx2VKZhUHjpkHxzkJoBmm28t9R_gKbnDmvAyEoOh_o_-l9FNxMzaOGtj_OREHPaq6Q9-raBNvqV1RJSMyi5Fi-eMhG7haruf-P7HdFBPBts1j4XaNgrJNMzQ9OWGHe6T9id899bXn6M0RiGuwX0XTaP8NQ20x44sAkSL1u0XdWAwT1IBHDhUyjtIIarQweS7O5v-xt2SdDa0IOmfvGBmKYZZeosx-xflBX-A6iJITqj5gwA 
API_VERSION: 1
API_PORT: 8080
POSTGRES_USER: gotodos
POSTGRES_PASSWORD: gotodos
POSTGRES_DB: gotodos
